# Generated by Django 4.0.5 on 2022-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=40)),
                ('template_id', models.CharField(max_length=50)),
                ('version', models.FloatField()),
                ('opened', models.BooleanField()),
                ('link_clicked', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Email Message',
                'ordering': ['-created_date'],
            },
        ),
    ]
