# Generated by Django 4.0.5 on 2022-06-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_emails', '0003_remove_transactionemail_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionemail',
            old_name='user',
            new_name='to_user',
        ),
    ]
