# Generated by Django 4.0.5 on 2022-06-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_emails', '0004_rename_user_transactionemail_to_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionemail',
            old_name='version',
            new_name='template_version',
        ),
    ]
