# Generated by Django 4.0.5 on 2022-06-06 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction_emails', '0005_rename_version_transactionemail_template_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionemail',
            old_name='to_user',
            new_name='to_email',
        ),
        migrations.CreateModel(
            name='EmailVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=8)),
                ('postmark_template_id', models.IntegerField()),
                ('changes', models.TextField()),
                ('total_opened', models.IntegerField()),
                ('total_link_clicks', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
