# Generated by Django 4.0.5 on 2022-06-07 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_emails', '0006_rename_to_user_transactionemail_to_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailversion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailversion',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
