# Generated by Django 4.0.5 on 2022-06-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_emails', '0009_alter_emailversion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailversion',
            old_name='email_name',
            new_name='email_alias',
        ),
        migrations.RemoveField(
            model_name='transactionemail',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='transactionemail',
            name='template_version',
        ),
        migrations.AddField(
            model_name='transactionemail',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction_emails.emailversion'),
            preserve_default=False,
        ),
    ]
