# Generated by Django 4.0.5 on 2022-06-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_emails', '0010_rename_email_name_emailversion_email_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionemail',
            name='link_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactionemail',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
