# Generated by Django 4.0.5 on 2022-06-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_emails', '0011_alter_transactionemail_link_clicked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionemail',
            old_name='to_email',
            new_name='to_user',
        ),
    ]
