# Generated by Django 4.0.5 on 2022-06-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_emails', '0012_rename_to_email_transactionemail_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionemail',
            name='to_email',
            field=models.CharField(default='damian@onehep.com', max_length=50),
            preserve_default=False,
        ),
    ]
